version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: armario
      POSTGRES_USER: armario
      POSTGRES_PASSWORD: armario
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - armario-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U armario"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      db:
        condition: service_healthy
    networks:
      - armario-network

volumes:
  pgdata:

networks:
  armario-network:
    driver: bridge 